---
kind: "AlertmanagerConfig"
api_family: "monitoring.coreos.com"
default_command: "alertmanagerconfigs"
command:
  - "almconfs"
  - "almconf"
listview:
  name: "Alertmanager Configs"
  group: "Observability"
  field_indexes:
    Normal:
      fields: ["namespace", "name", "age"]
      sortcolumn: "namespace"
