---
kind: "CiliumNodeConfig"
api_family: "cilium.io"
default_command: "ciliumnodeconfigs"
command:
  - "ciliumnodeconfs"
  - "ciliumnodeconf"
listview:
  name: "Cilium Node Configs"
  group: "Cilium"
  field_indexes:
    Normal:
      fields: ["namespace", "name", "age"]
      sortcolumn: "namespace"
infoview:
  name: "Cilium Node Config Info"
  infopad:
    row_indexes:
      Normal:
        fields: ["node_label_selector",
                 "node_set_based_selector",
                 "default_ip_pool"]
    rows:
      default_ip_pool:
        header: [["Default Pod ", ["main", "infoheader"]],
                 ["I", ["main", "infoheader_shortcut"]],
                 ["P Pool:", ["main", "infoheader"]]]
        path: "spec#defaults#ipam-default-ip-pool"
        default: "<unset>"
        type: "str"
      node_label_selector:
        header: [["Node La", ["main", "infoheader"]],
                 ["b", ["main", "infoheader_shortcut"]],
                 ["el Selector:", ["main", "infoheader"]]]
        paths:
          - path: ["spec#nodeSelector#matchLabels"]
            pathtype: "key_value"
            default: ["<none>"]
        formatter: "list"
        formatting:
          field_colors:
            - type: "key"
            - type: "value"
          field_separators:
            - type: "selector"
      node_set_based_selector:
        header: [["Node Set-based Selector:", ["main", "infoheader"]]]
        paths:
          - path: "spec#nodeSelector#matchExpressions"
            pathtype: "match_expression"
            default: "<none>"
        formatter: "list"
        formatting:
          field_colors:
            - type: "key"
            - type: "operator"
            - type: "value"
          field_separators:
            - type: "space"
            - type: "no_pad"
  shortcuts:
    "Default Pod IP Pool":
      key: "I"
      modifier: "shift"
      read_only: true
      helptext: "Open info page for default IP pool"
      action: "call"
      action_call: "resourceinfodispatch_with_lookup"
      action_args:
        _pass_obj: true
        kind: "CiliumPodIPPool"
        api_family: "cilium.io"
        name_path: "spec#defaults#ipam-default-ip-pool"
    "Defaults":
      key: "d"
      modifier: "shift"
      read_only: true
      helptext: "Show defaults"
      widget: "windowwidget"
      title: "Defaults:"
      headers: ["Key:", "Value:"]
      itemgetter: "get_key_value"
      itemgetter_args:
        path: "spec#defaults"
    "Node Label Selector":
      key: "b"
      read_only: true
      helptext: "Show node label selector"
      widget: "windowwidget"
      title: "Node Label Selector:"
      headers: ["Key:", "Value:"]
      itemgetter: "get_key_value"
      itemgetter_args:
        path: "spec#nodeSelector#matchLabels"
