---
kind: "FRRConfiguration"
api_family: "frrk8s.metallb.io"
default_command: "frrconfigurations"
command:
  - "frrconfs"
  - "frrconf"
listview:
  name: "FRR Configurations"
  group: "Network"
  field_indexes:
    Normal:
      fields: ["namespace", "name", "age"]
      sortcolumn: "namespace"
infoview:
  name: "FRR Configuration Info"
  infopad:
  logpad:
    infogetter: "logpad_formatted"
    infogetter_args:
      formatter: "format_yaml"
      path: "spec#bgp"
    timestamps: false
