---
kind: "HelmChartConfig"
api_family: "helm.cattle.io"
default_command: "helmchartconfigs"
listview:
  name: "Helm Chart Configs"
  group: "Rancher"
  field_indexes:
    Normal:
      fields: ["namespace", "name", "age"]
      sortcolumn: "namespace"
infoview:
  name: "Helm Chart Config Info"
  infopad:
    row_indexes:
      Normal:
        fields: ["failure_policy"]
    rows:
      failure_policy:
        header: [["Failure Policy:", ["main", "infoheader"]]]
        path: "spec#failurePolicy"
        default: "<unset>"
        type: "str"
  logpad:
    infogetter: "logpad_formatted"
    infogetter_args:
      formatter: "format_yaml"
      path: "spec#valuesContent"
    timestamps: false
