---
kind: "KubeletConfig"
api_family: "machineconfiguration.openshift.io"
default_command: "kubeletconfigs"
listview:
  name: "Kubelet Configs"
  group: "OpenShift"
  field_indexes:
    Normal:
      fields: ["name", "age"]
infoview:
  name: "Kubelet Config Info"
  infopad:
    row_indexes:
      Normal:
        fields: ["machine_config_pool_label_selector",
                 "machine_config_pool_set_based_selector"]
    rows:
      machine_config_pool_label_selector:
        header: [["Machine Config Pool La", ["main", "infoheader"]],
                 ["b", ["main", "infoheader_shortcut"]],
                 ["el Selector:", ["main", "infoheader"]]]
        paths:
          - path: ["spec#machineConfigPoolSelector#matchLabels"]
            pathtype: "key_value"
            default: ["<none>"]
        formatter: "list"
        formatting:
          field_colors:
            - type: "key"
            - type: "value"
          field_separators:
            - type: "selector"
      machine_config_pool_set_based_selector:
        header: [["Machine Config Pool Set-based Selector:",
                  ["main", "infoheader"]]]
        paths:
          - path: "spec#selector#matchExpressions"
            pathtype: "match_expression"
            default: "<none>"
        formatter: "list"
        formatting:
          field_colors:
            - type: "key"
            - type: "operator"
            - type: "value"
          field_separators:
            - type: "space"
            - type: "no_pad"
  logpad:
    infogetter: "logpad_formatted"
    infogetter_args:
      formatter: "format_yaml"
      path: "spec#kubeletConfig"
    timestamps: false
  shortcuts:
    "Machine Config Pool Label Selector":
      key: "b"
      read_only: true
      helptext: "Show Machine Config Pool label selector"
      widget: "windowwidget"
      title: "Machine Config Pool Label Selector:"
      headers: ["Key:", "Value:"]
      itemgetter: "get_key_value"
      itemgetter_args:
        path: "spec#machineConfigPoolSelector#matchLabels"
