---
- name: "List GPUs"
  hosts: "selection"
  vars:
    metadata:
      aliases:
        - "list-gpus"
        - "lsgpu"
      description: "List GPUs"
      playbook_types:
        - "cmtinv"
        - "inventory"
        - "nodes"
      category: "Information"
      summary:
        "Information gathering":
          - description: "Lists GPUs (VGA|Display)"
      read_only: true
  gather_facts: false
  become: true
  become_user: "root"
  tasks:
    - name: "Listing GPUs"
      ansible.builtin.shell: |
        if $( command -v lspci > /dev/null ); then
          lspci -nn -d "::0300"
          lspci -nn -d "::0301"
          lspci -nn -d "::0302"
          lspci -nn -d "::0380"
        else
          printf -- "[SKIP] lspci not installed\n"
        fi
      changed_when: false
