---
- name: "List PCI devices"
  hosts: "selection"
  vars:
    metadata:
      aliases:
        - "list-pci-devices"
        - "list_pci"
        - "list-pci"
        - "lspci"
      description: "List PCI devices"
      playbook_types:
        - "cmtinv"
        - "inventory"
        - "nodes"
      category: "Information"
      summary:
        "Information gathering":
          - description: "Lists PCI devices"
      read_only: true
  gather_facts: false
  tasks:
    - name: "Listing PCI devices"
      ansible.builtin.shell: |
        if $( command -v lspci > /dev/null ); then
          lspci -n -n
        else
          printf -- "[SKIP] lspci not installed\n"
        fi
      changed_when: false
