---
- name: "List CPU information"
  hosts: "selection"
  vars:
    metadata:
      aliases:
        - "list-cpus"
        - "lscpu"
      description: "List CPU information"
      playbook_types:
        - "cmtinv"
        - "inventory"
        - "nodes"
      category: "Information"
      summary:
        "Information gathering":
          - description: "Lists CPU information"
      read_only: true
  gather_facts: false
  tasks:
    - name: "Listing CPU information"
      ansible.builtin.shell: |
        if $( command -v lscpu > /dev/null ); then
          lscpu
        else
          printf -- "[SKIP] lscpu not installed\n"
        fi
      changed_when: false
